branch-defaults:
  main:
    environment: electronicComponentWarehouseMana-env
global:
  application_name: electronicComponentWarehouseManagementSystem
  default_region: us-east-1
  default_platform: Python 3.11
  workspace_type: Application
